-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 04:33:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_aluguel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_aluguel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_aluguel` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `banco_aluguel` ;

-- -----------------------------------------------------
-- Table `banco_aluguel`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro_cliente` DATE NULL DEFAULT NULL,
  `cpf_cliente` INT(11) NULL DEFAULT NULL,
  `tipo_cliente` INT(11) NULL DEFAULT NULL,
  `status_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `telefone_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`mtd_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`mtd_pagamento` (
  `idMtd_pagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMtd_pagamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`marca_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`marca_carro` (
  `idMarca` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`modelo_carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`modelo_carro` (
  `idModelo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(45) NULL DEFAULT NULL,
  `descricao_modelo` VARCHAR(45) NULL DEFAULT NULL,
  `idMarca` INT(11) NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_modelo_carro_marca_carro1_idx` (`idMarca` ASC),
  CONSTRAINT `fk_modelo_carro_marca_carro1`
    FOREIGN KEY (`idMarca`)
    REFERENCES `banco_aluguel`.`marca_carro` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`veiculo` (
  `idVeiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_chassi` VARCHAR(45) NULL DEFAULT NULL,
  `status_carro` VARCHAR(45) NULL DEFAULT NULL,
  `placa_carro` VARCHAR(45) NULL DEFAULT NULL,
  `cor_carro` VARCHAR(45) NULL DEFAULT NULL,
  `data_aquisicao` DATE NULL DEFAULT NULL,
  `quilometragem_veiculo` VARCHAR(45) NULL DEFAULT NULL,
  `valor_diaria` FLOAT NULL DEFAULT NULL,
  `valor_km` FLOAT NULL DEFAULT NULL,
  `idModelo` INT(11) NOT NULL,
  PRIMARY KEY (`idVeiculo`),
  INDEX `fk_veiculo_modelo_carro1_idx` (`idModelo` ASC),
  CONSTRAINT `fk_veiculo_modelo_carro1`
    FOREIGN KEY (`idModelo`)
    REFERENCES `banco_aluguel`.`modelo_carro` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`cargo_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`cargo_funcionario` (
  `idCargo_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NULL DEFAULT NULL,
  `salario_cargo` FLOAT NULL DEFAULT NULL,
  `descricao_cargo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCargo_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(45) NULL DEFAULT NULL,
  `idade_funcionario` INT(11) NULL DEFAULT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  `data_demissao` DATE NULL DEFAULT NULL,
  `email_funcionario` VARCHAR(45) NULL DEFAULT NULL,
  `senha_funcionario` VARCHAR(45) NULL DEFAULT NULL,
  `status_funcionario` VARCHAR(45) NULL DEFAULT NULL,
  `cpts_funcionario` VARCHAR(45) NULL DEFAULT NULL,
  `endereco` VARCHAR(100) NULL DEFAULT NULL,
  `idCargo_funcionario` INT(11) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_funcionario_cargo_funcionario1_idx` (`idCargo_funcionario` ASC),
  CONSTRAINT `fk_funcionario_cargo_funcionario1`
    FOREIGN KEY (`idCargo_funcionario`)
    REFERENCES `banco_aluguel`.`cargo_funcionario` (`idCargo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`aluguel` (
  `idAluguel` INT(11) NOT NULL AUTO_INCREMENT,
  `data_inicio_aluguel` DATETIME NULL DEFAULT NULL,
  `data_devolucao_aluguel` DATETIME NULL DEFAULT NULL,
  `quilometragem_inicial` FLOAT NULL DEFAULT NULL,
  `quilometragem_final` FLOAT NULL DEFAULT NULL,
  `status_aluguel` VARCHAR(45) NULL DEFAULT NULL,
  `valor_total` FLOAT NULL DEFAULT NULL,
  `nota_aluguel` VARCHAR(45) NULL DEFAULT NULL,
  `status_pagamento` INT(11) NULL DEFAULT NULL,
  `idCliente` INT(11) NOT NULL,
  `idMtd_pagamento` INT(11) NOT NULL,
  `idVeiculo` INT(11) NOT NULL,
  `idFuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idAluguel`),
  INDEX `fk_aluguel_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_aluguel_mtd_pagamento1_idx` (`idMtd_pagamento` ASC),
  INDEX `fk_aluguel_veiculo1_idx` (`idVeiculo` ASC),
  INDEX `fk_aluguel_funcionario1_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_aluguel_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `banco_aluguel`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_mtd_pagamento1`
    FOREIGN KEY (`idMtd_pagamento`)
    REFERENCES `banco_aluguel`.`mtd_pagamento` (`idMtd_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_veiculo1`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `banco_aluguel`.`veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `banco_aluguel`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`avarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`avarias` (
  `idAvarias` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao_avaria` VARCHAR(45) NULL DEFAULT NULL,
  `valor_avaria` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idAvarias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `banco_aluguel`.`veiculo_avarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_aluguel`.`veiculo_avarias` (
  `idVeiculo` INT(11) NOT NULL,
  `idAvarias` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idVeiculo`, `idAvarias`),
  INDEX `fk_veiculo_has_avarias_avarias1_idx` (`idAvarias` ASC),
  INDEX `fk_veiculo_has_avarias_veiculo_idx` (`idVeiculo` ASC),
  CONSTRAINT `fk_veiculo_has_avarias_veiculo`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `banco_aluguel`.`veiculo` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_has_avarias_avarias1`
    FOREIGN KEY (`idAvarias`)
    REFERENCES `banco_aluguel`.`avarias` (`idAvarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
